image: atlassian/default-image:4

pipelines:
  default:
    - parallel:
        - step:
            name: Build and Test
            script:
              - IMAGE_NAME="app"
              - docker build . --file Dockerfile --tag ${IMAGE_NAME}
            services:
              - docker
            caches:
              - docker
  branches:
    master:
      - step:
          name: Build and Test
          script:
            - IMAGE_NAME="app"
            - docker build . --file Dockerfile --tag ${IMAGE_NAME}
            - docker save ${IMAGE_NAME} --output "${IMAGE_NAME}.tar"
          services:
            - docker
          caches:
            - docker
          artifacts:
            - "*.tar"
      - step:
          name: Deploy to Dockerhub
          deployment: Production
          script:
            - echo ${DOCKERHUB_PASSWORD} | docker login --username "${DOCKERHUB_USERNAME}" --password-stdin
            - DOCKERHUB_NAMESPACE="tdmamb/sacvefor"
            - IMAGE_NAME="app"
            - IMAGE=${DOCKERHUB_NAMESPACE}:${IMAGE_NAME}
            - VERSION="1.1.1.build-${BITBUCKET_BUILD_NUMBER}"
            - docker load --input "${IMAGE_NAME}.tar"
            - docker tag "${IMAGE_NAME}" "${IMAGE}-latest"
            - docker tag "${IMAGE_NAME}" "${IMAGE}-${VERSION}"
            - docker push "${IMAGE}-latest"
            - docker push "${IMAGE}-${VERSION}"
          services:
            - docker
